repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
    - id: ruff
    - id: ruff-format

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-ast
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, qa, --branch, main]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]
